name = "Gruppe Adler Admin Messages (GC FORK)"
prefix = "grad_adminMessages"
author = "Global Conflicts"
files = [
    "mod.cpp",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip grad_adminMessages_{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"