name = "Gruppe Adler Admin Messages (GC FORK)";
author = "Global Conflicts";
tooltip = "Gruppe Adler Admin Messages";
tooltipOwned = "Gruppe Adler Admin Messages";
actionName = "GitHub";
action = "https://github.com/Global-Conflicts-ArmA/gc_adminMessages";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.8196, 0.5529, 0.1216, 1};